# Generated by Django 5.0.3 on 2024-03-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_author_created_date_author_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
