# Generated by Django 5.0.3 on 2024-03-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_author_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
