# Generated by Django 5.0.3 on 2024-05-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_libro_special_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
