# Generated by Django 5.0.3 on 2024-05-16 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_producto_special_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AlterField(
            model_name='libro',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.author'),
        ),
    ]
